// Catalogo de la tienda.
// Cada producto es un objeto literal y "especificaciones" es un sub-objeto,
// igual que el ejemplo del carro con "confort" que trabajamos en clase.

export const CATEGORIAS = ['Portatiles', 'Perifericos', 'Componentes', 'Monitores'];

export const PRODUCTOS = [
  {
    codigo: 1,
    nombre: 'Portatil Lenovo IdeaPad 3',
    categoria: 'Portatiles',
    marca: 'Lenovo',
    precio: 2450000,
    disponible: true,
    envioGratis: true,
    descripcion: 'Equipo liviano para estudio y ofimatica, con arranque rapido en SSD.',
    especificaciones: {
      procesador: 'Intel Core i5 de 12va generacion',
      memoria: '16 GB RAM',
      almacenamiento: 'SSD 512 GB',
      garantia: '12 meses',
    },
  },
  {
    codigo: 2,
    nombre: 'Portatil ASUS TUF Gaming A15',
    categoria: 'Portatiles',
    marca: 'ASUS',
    precio: 4890000,
    disponible: true,
    envioGratis: true,
    descripcion: 'Portatil gamer con refrigeracion reforzada y pantalla de 144 Hz.',
    especificaciones: {
      procesador: 'AMD Ryzen 7',
      memoria: '16 GB RAM',
      almacenamiento: 'SSD 1 TB',
      garantia: '24 meses',
    },
  },
  {
    codigo: 3,
    nombre: 'Teclado mecanico Redragon Kumara',
    categoria: 'Perifericos',
    marca: 'Redragon',
    precio: 185000,
    disponible: true,
    envioGratis: false,
    descripcion: 'Teclado mecanico compacto con switches azules y retroiluminacion.',
    especificaciones: {
      tipo: 'Mecanico TKL',
      conexion: 'USB cableado',
      switches: 'Outemu azul',
      garantia: '6 meses',
    },
  },
  {
    codigo: 4,
    nombre: 'Mouse inalambrico Logitech M720',
    categoria: 'Perifericos',
    marca: 'Logitech',
    precio: 210000,
    disponible: true,
    envioGratis: false,
    descripcion: 'Mouse multidispositivo que cambia entre tres equipos con un boton.',
    especificaciones: {
      tipo: 'Ergonomico',
      conexion: 'Bluetooth y receptor USB',
      bateria: 'Hasta 24 meses',
      garantia: '12 meses',
    },
  },
  {
    codigo: 5,
    nombre: 'Memoria RAM Kingston Fury 16 GB',
    categoria: 'Componentes',
    marca: 'Kingston',
    precio: 320000,
    disponible: true,
    envioGratis: false,
    descripcion: 'Modulo DDR4 para ampliar el rendimiento en tareas pesadas.',
    especificaciones: {
      capacidad: '16 GB',
      tecnologia: 'DDR4 3200 MHz',
      formato: 'DIMM escritorio',
      garantia: 'De por vida',
    },
  },
  {
    codigo: 6,
    nombre: 'Disco solido Samsung 980 1 TB',
    categoria: 'Componentes',
    marca: 'Samsung',
    precio: 415000,
    disponible: false,
    envioGratis: true,
    descripcion: 'Unidad NVMe que reduce los tiempos de carga del sistema operativo.',
    especificaciones: {
      capacidad: '1 TB',
      interfaz: 'NVMe PCIe 3.0',
      lectura: '3500 MB/s',
      garantia: '60 meses',
    },
  },
  {
    codigo: 7,
    nombre: 'Monitor LG UltraGear 24"',
    categoria: 'Monitores',
    marca: 'LG',
    precio: 890000,
    disponible: true,
    envioGratis: true,
    descripcion: 'Monitor de 144 Hz con tiempo de respuesta de 1 ms.',
    especificaciones: {
      tamano: '24 pulgadas',
      resolucion: '1920 x 1080',
      frecuencia: '144 Hz',
      garantia: '36 meses',
    },
  },
  {
    codigo: 8,
    nombre: 'Monitor Samsung ViewFinity 27"',
    categoria: 'Monitores',
    marca: 'Samsung',
    precio: 1290000,
    disponible: true,
    envioGratis: true,
    descripcion: 'Panel IPS con alta fidelidad de color para diseno y programacion.',
    especificaciones: {
      tamano: '27 pulgadas',
      resolucion: '2560 x 1440',
      frecuencia: '75 Hz',
      garantia: '24 meses',
    },
  },
];
